//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuyenbay_vandon_data_backup
    {
        public long ID { get; set; }
        public long IDCHUYENBAY { get; set; }
        public System.DateTime FLIGHTDATE { get; set; }
        public string CARRIER { get; set; }
        public string FLIGHTNO { get; set; }
        public string ORIGIN { get; set; }
        public string DESTINATION { get; set; }
        public string MAWB_NO { get; set; }
        public string M_TENNGUOIGUI { get; set; }
        public string M_TENNGUOINHAN { get; set; }
        public string M_MOTAHANGHOA { get; set; }
        public Nullable<int> M_SOKIEN { get; set; }
        public Nullable<decimal> M_GROSSWEIGHT { get; set; }
        public string M_SANBAYDI { get; set; }
        public string M_SANBAYDEN { get; set; }
        public Nullable<int> M_VERSION { get; set; }
        public string M_TENDAILY { get; set; }
        public string H_SOMAWB { get; set; }
        public string H_SOHWB { get; set; }
        public string H_TENNGUOIGUI { get; set; }
        public string H_TENNGUOINHAN { get; set; }
        public Nullable<int> H_SOKIEN { get; set; }
        public Nullable<decimal> H_TRONGLUONG { get; set; }
        public string H_NOIDI { get; set; }
        public string H_NOIDEN { get; set; }
        public string H_MOTAHANGHOA { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
    }
}
