//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuyenbay_tobay_data_backup
    {
        public long IDCHUYENBAY { get; set; }
        public long FI_IDTTCHUNG { get; set; }
        public long IDTOBAY { get; set; }
        public string HO { get; set; }
        public string TENDEM { get; set; }
        public string TEN { get; set; }
        public string GIOITINH { get; set; }
        public string QUOCTICH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string SOGIAYTO { get; set; }
        public string LOAIGIAYTO { get; set; }
        public string NOICAP { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        public Nullable<int> TBVERSION { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
        public string SOHIEU { get; set; }
        public Nullable<System.DateTime> NGAYBAY { get; set; }
        public string NOIDI { get; set; }
        public string NOIDEN { get; set; }
    }
}
