//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuyenbay_pnr_data_backup
    {
        public long ID { get; set; }
        public string FI_MADATCHO { get; set; }
        public Nullable<System.DateTime> FI_NGAYDATCHO { get; set; }
        public string FI_THONGTINVE { get; set; }
        public string FI_LICHTRINHBAY { get; set; }
        public string FI_HANHKHACHTHUONGXUYEN { get; set; }
        public string FI_MADAILYBANVE { get; set; }
        public string FI_MANGUOIDATCHO { get; set; }
        public string FI_MADOANBAY { get; set; }
        public string FI_MATACHCHO { get; set; }
        public string FI_SOGHEYEUCAU { get; set; }
        public string FI_SOGHEDADAT { get; set; }
        public string FI_THONGTINHANHLY { get; set; }
        public string FI_GHICHUCHUNG { get; set; }
        public string FI_THONGTINBOSUNG { get; set; }
        public string FI_DICHVUDACBIET { get; set; }
        public string FI_THONGTINAPIKHAC { get; set; }
        public string FI_NHOMCANHAN { get; set; }
        public Nullable<int> FI_SOHANHKHACH { get; set; }
        public string FI_LICHSU { get; set; }
        public string FI_THANHTOAN { get; set; }
        public string FI_SOCHUYENBAY { get; set; }
        public string FI_IDHANHKHACH { get; set; }
        public Nullable<int> FI_STATUS { get; set; }
        public string FI_LICHBAY { get; set; }
        public Nullable<System.DateTime> FI_NGAYBAY { get; set; }
        public string FI_MACANGHANGKHONGDI { get; set; }
        public string FI_MACANGHANGKHONGDEN { get; set; }
        public string FI_IDHANHKHACH1 { get; set; }
        public string FI_TENHANHKHACH { get; set; }
        public string FI_TENKHAC { get; set; }
        public string FI_DIACHI { get; set; }
        public string FI_SODIENTHOAI { get; set; }
        public string FI_EMAIL { get; set; }
        public string FI_CHITIETLIENHE { get; set; }
        public string FI_SOCHUYENBAY1 { get; set; }
        public string FI_IDCHUYENBAY { get; set; }
        public string FI_REFID { get; set; }
        public Nullable<int> FI_SOLANGUIFILE { get; set; }
        public string FI_THOIGIANGUIFILE { get; set; }
        public Nullable<int> FI_VERSION { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
    }
}
