//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuyenbay_hanhkhach
    {
        public long ID_CHUYENBAY { get; set; }
        public string SOHIEU { get; set; }
        public Nullable<System.DateTime> FLIGHTDATE { get; set; }
        public string CARRIERCODE { get; set; }
        public string CARRIERNAME { get; set; }
        public string MANOIDI { get; set; }
        public string TENNOIDI { get; set; }
        public string MANOIDEN { get; set; }
        public string TENNOIDEN { get; set; }
        public long IDHANHKHACH { get; set; }
        public long IDCHUYENBAY { get; set; }
        public string MADATCHO { get; set; }
        public string GIOITINH { get; set; }
        public string HO { get; set; }
        public string TENDEM { get; set; }
        public string TEN { get; set; }
        public string QUOCTICH { get; set; }
        public string SOGIAYTO { get; set; }
        public string LOAIGIAYTO { get; set; }
        public string NOICAP { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string NOIDI { get; set; }
        public string NOIDEN { get; set; }
        public string HANHLY { get; set; }
        public Nullable<int> HK_VERSION { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
        public Nullable<int> CB_HK { get; set; }
        public Nullable<int> CB_XK { get; set; }
        public Nullable<int> CB_NK { get; set; }
        public Nullable<int> CB_DICHUYEN_1 { get; set; }
        public Nullable<int> CB_DICHUYEN { get; set; }
    }
}
