//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuyenbay_hh
    {
        public long ID { get; set; }
        public long ID_CHUYENBAY { get; set; }
        public string SOHIEU { get; set; }
        public System.DateTime FLIGHTDATE { get; set; }
        public string CARRIERCODE { get; set; }
        public string CARRIERNAME { get; set; }
        public string MANOIDI { get; set; }
        public string TENNOIDI { get; set; }
        public string MANOIDEN { get; set; }
        public string TENNOIDEN { get; set; }
        public string FI_MAQUACANH { get; set; }
        public long IDHANGHOA { get; set; }
        public long ID_HHCT { get; set; }
        public string FI_SOAWB { get; set; }
        public Nullable<int> FI_SOKIEN { get; set; }
        public string FI_MOTA { get; set; }
        public string FI_SHC { get; set; }
        public Nullable<decimal> TRONGLUONG { get; set; }
        public string NOIDIHH { get; set; }
        public string NOIDENHH { get; set; }
        public Nullable<int> FI_LOAIHANG { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
    }
}
