//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hang_hang_khong
    {
        public int id { get; set; }
        public string FI_TENHANGHANGKHONG { get; set; }
        public string FI_NUOC { get; set; }
        public string FI_MAICAO { get; set; }
        public string FI_MAIATA { get; set; }
        public string FI_MAHANGHK { get; set; }
        public Nullable<int> FI_HOATDONG { get; set; }
    }
}
