//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mien_thue
    {
        public long id { get; set; }
        public string ho { get; set; }
        public string ten_dem { get; set; }
        public string ten { get; set; }
        public string ho_va_ten { get; set; }
        public string so_giay_to { get; set; }
        public string loai_giay_to { get; set; }
        public string gioi_tinh { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string quoc_tich { get; set; }
        public string chuyen_bay { get; set; }
        public Nullable<long> id_chuyenbay { get; set; }
        public Nullable<System.DateTime> ngay_huong { get; set; }
        public string tieu_chuan { get; set; }
        public Nullable<System.DateTime> ngay_bay { get; set; }
        public string noi_di { get; set; }
        public string noi_den { get; set; }
    }
}
