//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SChuyenBay
    {
        public int Id { get; set; }
        public string ChuyenBay { get; set; }
        public int GioKhoiHanh_Gio { get; set; }
        public Nullable<int> GioKhoiHanh_Phut { get; set; }
        public int GioKetThuc_Gio { get; set; }
        public Nullable<int> GioKetThuc_Phut { get; set; }
    }
}
