//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SChuyenBay
    {
        public int Id { get; set; }
        public System.DateTime Ngay { get; set; }
        public string ChuyenBay { get; set; }
        public string ChangBay { get; set; }
        public Nullable<int> SOBT { get; set; }
        public Nullable<int> EOBT { get; set; }
        public string DaoHanhLy { get; set; }
        public string CuaSo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
