//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMienThue
    {
        public decimal Id { get; set; }
        public string HoTen { get; set; }
        public string SoGiayTo { get; set; }
        public string LoaiGiayTo { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string QuocTich { get; set; }
        public Nullable<System.DateTime> NgayHuong { get; set; }
        public Nullable<decimal> TieuChuan { get; set; }
        public string ChuyenBay { get; set; }
        public string NoiDi { get; set; }
        public string NoiDen { get; set; }
        public Nullable<System.DateTime> NgayBay { get; set; }
        public Nullable<long> IdChuyenBay { get; set; }
    }
}
