//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPermission()
        {
            this.SRolePermissions = new HashSet<SRolePermission>();
        }
    
        public int Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string ViewName { get; set; }
        public Nullable<int> Enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRolePermission> SRolePermissions { get; set; }
    }
}
