//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STrongDiem_LichSu
    {
        public decimal Id { get; set; }
        public decimal DoiTuongId { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public string DauHieuRuiRo { get; set; }
        public string YeuCauNghiepVu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SDoiTuongTrongDiem SDoiTuongTrongDiem { get; set; }
    }
}
