//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemEntities : DbContext
    {
        public SystemEntities()
            : base("name=SystemEntities")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SPhongBan> SPhongBans { get; set; }
        public virtual DbSet<SRole> SRoles { get; set; }
        public virtual DbSet<SUser> SUsers { get; set; }
        public virtual DbSet<SUserRole> SUserRoles { get; set; }
        public virtual DbSet<SPermission> SPermissions { get; set; }
        public virtual DbSet<SRolePermission> SRolePermissions { get; set; }
    }
}
