//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNoiBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warning_history
    {
        public int id { get; set; }
        public string so_giay_to { get; set; }
        public string loai_giay_to { get; set; }
        public string ho { get; set; }
        public string ten_dem { get; set; }
        public string ten { get; set; }
        public string quoc_tich { get; set; }
        public Nullable<System.DateTime> ngay_canh_bao { get; set; }
        public string so_hieu { get; set; }
        public string ngay_bay { get; set; }
        public string hanh_ly { get; set; }
        public string ho_va_ten { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string gioi_tinh { get; set; }
        public string ghi_chu { get; set; }
        public string yc_nghiep_vu { get; set; }
        public Nullable<int> mail_status { get; set; }
        public Nullable<int> is_trong_diem { get; set; }
    }
}
